defaultBufferSize: 2097152
defaultSlotTimeout: 300000
cluster: false
awsUploadRatePerStreamInMB: 10
environmentProvider: com.pinterest.memq.core.config.LocalEnvironmentProvider
topicConfig:
    - topic: test
      ringBufferSize: 1024
      outputParallelism: 4
      batchSizeMB: 1
      batchMilliSeconds: 1
      storageHandlerName: filesystem
      storageHandlerConfig:
        retryTimeoutMillis: 5000
        storageDirs: /Volumes/RAMDisk/val
        maxAttempts: 2
        disableNotifications: true
        bucket: <mybucket-name>
        path: test/TestTopic
        region: us-east-1
        notificationServerset: /tmp/serverset/notification.serverset
        notificationTopic: TestTopicNotifications