name: memq-build-validation

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'corretto'
      - name: mvn-test
        run: mvn clean test --file pom.xml